### ISSUE TITLE
XcpCreateEvent cycleTimeNs parameter mismatch in C_Demo

### ISSUE THREAD

**Issue by MarioVolarevic** [vectorgrp/XCPlite#50]
Hello, I noticed an issue, but I'm not sure which part is actually wrong, so I'm reporting it here.

Based on this diff I see that you modifed what is requested in the XcpCreateEvent method

![image](https://github.com/vectorgrp/XCPlite/assets/1615417/05cb7da2-a260-472c-8961-dcba40f10a14)

But in C_Demo example, what is actually sent to the function is:
`    
gXcpEvent_EcuCyclic = XcpCreateEvent("ecuTask", ECU_TASK_CYCLE_TIME_US/CLOCK_TICKS_PER_US, 0, 0, 0);
` 
which is actually value in ms and this incorrectly creates the unit and channel cycle time in a2l.

Now, the question is if only the demo parameter is incorrectly calculated or functionality for calculating the unit and cycleTime inside XcpCreateEvent also has to be modified?

**Comment by RainerZ** [comment]
Hello,
you are right. The code in the C_Demo example is incorrect. The cycletime value should be in ns. 
The semantic modification of the cycletime parameter in XcpCreateEvent from us to ns happened in commit 876aca1f 2022-03-02 20:22. The code in ecu.c is wrong since this commit.
The cycle time information of an event will only be written to the A2l file. CANape does not need it or check it to create a DAQ setup, unless packed mode is used. 
 
Thanks




Thanks
